<?php

/**
 * CompteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Compte');
    }
}