<?php

/**
 * DelegueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DelegueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DelegueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Delegue');
    }
}