<?php

/**
 * MedecinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedecinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedecinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medecin');
    }
}