<?php

/**
 * MedicamentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicamentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicamentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medicament');
    }
}