<?php

/**
 * RapportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RapportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RapportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rapport');
    }
}