<?php

/**
 * VisMedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisMedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VisMedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VisMed');
    }
}