<?php

/**
 * CompteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Compte');
    }

    public function getDelegatesComptes($type=null){// type de compte
    	$q = Doctrine_Query::create() // Création de la requête
        ->select('c.login, c.passwd,d.nom, d.prenom, d.dateEmbauche,d.image_url')
        ->from('Compte c')
        ->leftJoin('c.Delegue d');// On joint les deux tables.
        if($type!=null){
        	$q->addWhere('type = ?', $type);
        }
        return $q;
    }
}