<?php

/**
 * DelegueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DelegueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DelegueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Delegue');
    }

    public function mesDelegues($id){// type de compte
    	$q = Doctrine_Query::create() // Création de la requête
        ->select('d.nom,d.prenom')
        ->from('Delegue d')
        ->where('d.Del_id_delegue= ?', $id);// On joint les deux tables.
        return $q;
    }
}