<?php

/**
 * MedecinTable
 * @author : Yassine ELQANDILI
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedecinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedecinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medecin');
    }

    /**
     * @param $id : du docteur 
     *
     */
    public function getDoctors($id=null){
    	$q = Doctrine_Query::create()
    		->from("Medecin m")
    		->leftJoin("m.Secteur s");
        if ($id!=null) {
            $q->addWhere("id_medecin = ?", $id);
        }
        return $q;
    }
}