<?php

/**
 * MedicamentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicamentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicamentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medicament');
    }

    /**
     * @param : etat d'un médicament 0 normale et -1 pour etat supprimé
     *
     */
    public function getDrugs($etat=0){
    	$q = Doctrine_Query::create()
    		->from('Medicament')
    		->where('etat=?', $etat);
    	return $q;
    }
}