<?php

/**
 * MedTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedType');
    }
    public function getTypes($id){
    	$q = Doctrine_Query::create() // Création de la requête
        ->select('t.libelle, mt.id_medecin')
		->from('MedType mt')
		->leftJoin('mt.Type t') // On joint les deux tables.
		->where('id_medecin= ?', $id);
		return $q;
    }
}