<?php

/**
 * PersonneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Personne');
    }
}