<?php

/**
 * QteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Qte');
    }
}