<?php

/**
 * RapportTable
 * 
 * @author Yassine ELQANDILI 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RapportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RapportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rapport');
    }
    function getAllById_delegue($id){
		$q = Doctrine_Query::create()
			->select("r.id_rapport, r.date, r.introduction, r.conclusion")
			->from("rapport r")
			->where("id_delegue = ?", $id);
		return $q;
	}
    public function getMyDelegatesReports($id, $date=null){
        $q = Doctrine_Query::create()
            ->select("d.id_delegue, r.date, r.introduction, r.conclusion")
            ->leftJoin("Rapport r")
            ->leftJoin("r.Delegue d")
            ->where("d.Del_id_delegue = ?", $id);
        if($date!=null){
            $q->addWhere("r.date = ?", $date);
        }
        return $q;
    }
}