<?php

/**
 * SecteurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SecteurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SecteurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Secteur');
    }

    /**
     * @param id : id_secteur auquelle appartiennet les sous secteur (Id de Marrakech par rapport a Sidi Youssef)
     */
    public function getSubSectors($id){
    	$q = Doctrine_Query::create()
    		->from("Secteur");
    	if($id==null){
    		$q->addWhere("Sec_id_secteur is null");
    	}else{
    		$q->addWhere("Sec_id_secteur= ?", $id);
    	}
    	return $q;
    }
}